apiVersion: apps/v1
kind: Deployment
metadata:
  name: online-cv-chatbot
spec:
  replicas: 1
  selector:
    matchLabels:
      app: online-cv-chatbot
  template:
    metadata:
      labels:
        app: online-cv-chatbot
    spec:
      containers:
      - name: online-cv-chatbot
        image: online-cv-with-chatbot:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 5000
        resources:
          limits:
            memory: "512Mi"
            cpu: "500m"
          requests:
            memory: "256Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: online-cv-chatbot-service
spec:
  type: NodePort
  selector:
    app: online-cv-chatbot
  ports:
  - protocol: TCP
    port: 5000
    targetPort: 5000
    nodePort: 30000
